# TravisCI configuration for nexcess/limit-orders

if: 'branch = develop OR branch = master'

language: 'php'
os:
  - 'linux'
# 18.04 Bionic: PHP 7.1 - 8.0
dist: 'bionic'

services:
  - mysql

php:
  - '8.0'
  - '7.4'
  - '7.3'
  - '7.2'
  - '7.1'

# To keep the test matrix from exploding over time,
# we'll actively test against the latest three releases,
# then cherry-pick what to test across older ones.
env:
  jobs:
    - WP_VERSION: 'latest'
      WC_VERSION: '5.1'
    - WP_VERSION: 'latest'
      WC_VERSION: '5.0'
    - WP_VERSION: 'latest'
      WC_VERSION: '4.9'
    - WP_VERSION: 'latest'
      WC_VERSION: '3.9.3'

_shared_install_xenial_php70: &install_xenial_php70
  dist: 'xenial'
  php: '7.0'
  install:
     - 'composer remove --dev --no-update szepeviktor/phpstan-wordpress'
     - 'composer update --no-interaction --no-ansi --prefer-source --prefer-lowest'
     - |
       bash vendor/bin/install-wp-tests.sh wordpress_test root "" localhost "$WP_VERSION"
       if dpkg --compare-versions "$WC_VERSION" lt "4.8"; then composer self-update --1; fi
       DEBUG=1 bash tests/bin/install-woocommerce.sh "$WC_VERSION"

jobs:
  fast_finish: true
  include:
    - name: 'PHP 7.0 WP latest WC 5.1'
      env:
        - WP_VERSION: 'latest'
          WC_VERSION: '5.1'
      <<: *install_xenial_php70
 
    - name: 'PHP 7.0 WP latest WC 5.0'
      env:
        - WP_VERSION: 'latest'
          WC_VERSION: '5.0'
      <<: *install_xenial_php70
 
    - name: 'PHP 7.0 WP latest WC 4.9'
      env:
        - WP_VERSION: 'latest'
          WC_VERSION: '4.9'
      <<: *install_xenial_php70
 
    - name: 'PHP 7.0 WP latest WC 3.9.3'
      env:
        - WP_VERSION: 'latest'
          WC_VERSION: '3.9.3'
      <<: *install_xenial_php70
 
    - name: 'Coding Standards'
      php: '7.4'
      install:
        - 'composer install --no-interaction --no-ansi --prefer-source'
      script:
        - 'composer test:standards'

    - name: 'Static Code Analysis'
      php: '7.4'
      install:
        - 'composer install --no-interaction --no-ansi --prefer-source'
      script:
        - 'composer test:analysis'

    - name: 'Minimum requirements'
      env:
        - WP_VERSION: '5.3'
          WC_VERSION: '4.4'
      <<: *install_xenial_php70

    - name: 'Bleeding Edge'
      php: '8.0'
      env:
        - WP_VERSION: 'trunk'
          WC_VERSION: 'latest'
  allow_failures:
    - name: 'Bleeding Edge'

cache:
  directories:
    - '$HOME/.composer/cache'

before_install:
  - 'phpenv config-rm xdebug.ini'
  - 'composer validate --strict'

install:
  - 'composer install --no-interaction --no-ansi --prefer-source'
  - |
    bash vendor/bin/install-wp-tests.sh wordpress_test root "" localhost "$WP_VERSION"
    if dpkg --compare-versions "$WC_VERSION" lt "4.8"; then composer self-update --1; fi
    DEBUG=1 bash tests/bin/install-woocommerce.sh "$WC_VERSION"

script:
  - 'composer test:unit'

notifications:
  email:
    on_success: 'never'
    on_failure: 'change'
